name: polkawallet_plugin_laminar
description: A new Flutter package project.
version: 0.1.5
author:
homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  flutter_svg: ^0.19.3
  get_storage: ^1.2.1
  graphql_flutter: ^3.1.0
  polkawallet_sdk: ^0.1.4
#  polkawallet_sdk:
#    path: ../sdk
  polkawallet_ui:
    git:
      url: https://github.com/polkawallet-io/ui.git
      ref: c4346ecf37f277d6b61480f4782a9e78c99c68e2
#    path: ../ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  mobx_codegen: ^1.1.1
  json_serializable: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - lib/js_service_laminar/dist/main.js
    - assets/images/logo.png
    - assets/images/logo_gray.png
    - assets/images/flow.svg
    - assets/images/LAMI.png
    - assets/images/AUSD.png
    - assets/images/swap.svg
    - assets/images/loan.svg
    - assets/images/faucet.svg
    - assets/images/assets_up.png
    - assets/images/assets_down.png

  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
